[build]
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables needed:
# GITHUB_TOKEN - Personal access token with repo permissions
# GITHUB_REPO_OWNER - Repository owner (default: reidwcoleman)
# GITHUB_REPO_NAME - Repository name (default: eplnewshub.com)